spring:
  application:
    name: raincat-order-examples
  profiles:
    active: druid

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: false